# Generated by Django 5.0.3 on 2024-04-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='emp',
        ),
    ]
