# Generated by Django 5.0.3 on 2024-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combon', '0002_alter_emp_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dhan',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='dhan',
            old_name='username1',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='dhan',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dhan',
            name='phoneno',
            field=models.CharField(max_length=15),
        ),
    ]
