# Generated by Django 5.0.3 on 2024-04-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combon', '0003_rename_password1_dhan_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhan',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dhan',
            name='username',
        ),
    ]
