# Generated by Django 5.0.3 on 2024-05-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combon', '0004_remove_dhan_password_remove_dhan_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhan',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
